---
repos:
  - repo: local
    hooks:
      - id: validate
        name: validate asset JSON-LD
        entry: make validate
        language: system
        pass_filenames: false
        always_run: true
