name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers the workflow on version tags

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          lfs: true
          submodules: recursive

    - name: Checkout LFS objects
      run: git lfs checkout

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Setup and validate
      run: |
        make setup
        make validate

    - name: Create zip file
      run: make asset zip

    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v2
      with:
        files: "*.zip"
        generate_release_notes: true
