name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers the workflow on version tags

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          lfs: true
          submodules: recursive

    - name: Checkout LFS objects
      run: git lfs checkout

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Setup and validate
      run: |
        make setup
        make validate

    - name: Create zip file
      run: make asset zip

    - name: Get asset name
      id: asset_name
      run: |
        echo "zip=$(ls *.zip)" >> $GITHUB_OUTPUT
 
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ steps.asset_name.outputs.zip }}
        asset_name: ${{ steps.asset_name.outputs.zip }}
        asset_content_type: application/zip
